modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="testmod"
version="1.0.0"
displayName="TestMod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="htbrdd, MCreator"

[[dependencies.testmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



